[tool.poetry]
name = "skyproject"
version = "0.1.0"
description = ""
authors = ["Andrey <yuryev@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
